version: "3"

services:

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:     
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 8000:8000

  
